services:

  backend:
    build: ./backend
    container_name: django-backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    command: >
      sh -c "
      sleep 5 &&
      python cargar_heroes.py &&
      python manage.py runserver 0.0.0.0:8000
      "
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./frontend
    container_name: react-frontend
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5174:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
